services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rest_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/rest_service?sslmode=disable
    volumes:
      - .:/app
      - /app/vendor  # Если используешь модули
volumes:
  postgres_data:
